name: Continuous Integration

on:
  pull_request: { branches: [ "main" ] }
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  gen:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ foo, bar ]
    steps:
    - name: Output Value
      id: value
      run: echo "${{ matrix.component }}-value=Some Value for ${{ matrix.component }}" >>"$GITHUB_OUTPUT"
    outputs:
      foo-value: ${{ steps.digest.outputs.foo-value }}
      bar-value: ${{ steps.digest.outputs.bar-value }}

  use:
    needs: [ gen ]
    runs-on: ubuntu-latest
    env:
      VAL: ghcr.io/${{ github.repository_owner }}/fts/${{ matrix.agent }}
    strategy:
      matrix:
        component: [ foo, bar ]
    steps:
    - name: Print
      run: echo "${VAL}"
