name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  path:
    runs-on: ubuntu-latest
    steps:
    - run: | 
        echo "${PATH}"
        echo "${HOME}"
        ls ${HOME}/
        ls ${HOME}/.local
