name: Continuous Integration

on:
  pull_request: { branches: [ "main" ] }
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  gen:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ foo, bar ]
    steps:
    - name: Output Value
      id: value
      run: echo "${{ matrix.component }}-value=Some Value for ${{ matrix.component }}" >>"$GITHUB_OUTPUT"
    outputs:
      foo-value: ${{ steps.value.outputs.foo-value }}
      bar-value: ${{ steps.value.outputs.bar-value }}

  use:
    needs: [ gen ]
    runs-on: ubuntu-latest
    env:
      VAL: ${{ needs.gen.outputs[format('%s-value', matrix.component)] }}
      VAL_FOO: ${{ needs.gen.outputs.foo-value}}
      VAL_BAR: ${{ needs.gen.outputs.bar-value }}
    strategy:
      matrix:
        component: [ foo, bar ]
    steps:
    - name: Print
      env:
        VAL_LOCAL: ${{ needs.gen.outputs[format('%s-value', matrix.component)] }}
      run: |
        echo "${VAL}"
        echo "${VAL_LOCAL}"
        echo "${VAL_FOO}"
        echo "${VAL_BAR}"

  use-all:
    needs: [ gen ]
    runs-on: ubuntu-latest
    steps:
    - name: Print
      run: echo '${{ toJSON(needs.gen.outputs) }}'
