name: Continuous Integration

on:
  pull_request: { branches: [ "main" ] }
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
    - id: generate-image-tag
      env:
        ref_name: "${{ github.ref_name }}"
        head_ref: "${{ github.head_ref }}"
      run: |
        ref_name="${head_ref:-${ref_name/main/latest}}"
        echo "ref: ${ref_name}"
        echo "::set-output name=imageTag::${ref_name#v}"
        echo "imageTag: ${ref#v}"
