name: Continuous Integration

on:
  pull_request: { branches: [ "main" ] }
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: Some Failing Step
      run: exit 1

  second:
    runs-on: ubuntu-latest
    needs: [ first ]
    if: always()
    steps:
    - name: Some Job in Need
      run: |
        if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} == true ]]; then
          echo "One or more jobs have failed or been cancelled"
          exit 1
        else
          echo "All jobs completed successfully"
        fi
