name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    tags: [ "*" ]

permissions: read-all

jobs:
  path:
    runs-on: life-standard-16
    steps:
    - run: |
        uname -u
        echo "${PATH}"
        echo "${HOME}"
        ls ${HOME}/
